### PR TITLE
Adg5 62 Bug - fixed

### PR DESCRIPTION
**Pull request by EmmaStalberg**

### CODE REVIEW

**Comment by EmmaStalberg** [comment]
- words are shuffled 
- fast clicking is permitted
- ...

**Comment by chiranjibee** [comment]
@EmmaStalberg 

This works great now. 
Can it be combined with the previous iteration where the words on both columns don't disappear after being "correctly" clicked on? Just once both words are correctly selected - disable the buttons?

**Comment by EmmaStalberg** [comment]
Yeah I was considering that as well. I just feel like if we go back and only use the disabling of the buttons when they are correct, it is then very confusing when you continue since the disabling of the buttons can be due to two reasons - either they are correclty clicked and shouldn't be considered, or they are just disabled for now because you have already clicked a word in that language (first or wrong). Hence, I instead did so that they disappeared (like it is in duolingo i think?). I also tried to do different types of disabling depending on if they were disabled due to correctness or to "already chosen", but that also looked quite confusing. 

If I should go back to not making them disappear, do you have any suggestions on how to make the disabled mode look in the two different variants? I didn't manage to come up with a good idea that didn't make it more confusing....

**Comment by chiranjibee** [comment]
Yeah, that’s true. I’m not sure how to proceed either.

I just checked, only disables the words only when correct.

@stihan01 Can you provide some suggestions?

**Review by stihan01 — APPROVED** [review]
While i liked when the buttons only were disabled and did not disappear, i definetely see your point with it being confusing that the disabled buttons can mean two different things. I think you have solved it in a good way, i don't really know what else to do. I'll approve it :)

**Pull request merged**
